Vagrant.configure("2") do |config|
  config.vm.define "sys-design-rate-limiter" # vagrant cli
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "sys-design-rate-limiter" # virtualbox GUI
  end

  config.vm.provider :docker do |d|
    d.image = "redis"
    d.has_ssh = false
    d.remains_running = true
  end
  
  config.vm.provision "docker" do |d|
    d.run "redis",
        args: "-p 6379:6379"
  end

  # forward more ports to guest VM here
  config.vm.network "forwarded_port", guest: 6379, host: 6379

  # IMP - ctrl+c over vagrant (v2.3.4) ssh will exit session
  #   use this snippet to setup access over regular ssh
  #   https://github.com/hashicorp/vagrant/issues/12908
  #     vagrant ssh-config --host <vm_name> > ~/.ssh/config.d/<vm_name>
  #     ssh <vm_name>
end